title: Alastor Collins
description: Business Analyst
site_title: 'Business Analytics Portfolio - Alastor Collins'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: mralcollins
linkedin_url: https://www.linkedin.com/in/alastor-collins
email: mr.al.collins@icloud.com

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 
